source 'https://rubygems.org'
#ruby-gemset=railstutorial_rails_4_0

gem 'rails', '4.1.0'
gem 'bootstrap-sass', '3.1.1.0'
gem 'sprockets', '2.11.0'
gem 'bcrypt', '3.1.7'

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails', '2.14.2'
  gem 'guard-rspec', '4.2.8'
  gem 'spring'

  gem 'spork-rails', '4.0.0'
  gem 'guard-spork', '1.5.1'
  gem 'childprocess', '0.5.2'
end

group :test do
  gem 'selenium-webdriver', '2.41.0'
  gem 'capybara', '2.2.1'

  # This gem is for use in a windowing environment
  #gem 'libnotify', '0.8.2'

  gem 'factory_girl_rails', '4.4.1'
end

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
# this messes with javascript actions on <a> tags
#gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

group :doc do
  gem 'sdoc', '~> 0.4.0', require: false
end

group :production do
  gem 'rails_12factor', '0.0.2'
  gem 'pg', '0.17.1'
end
